<?php
/**
 * Role
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.13.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Role Class Doc Comment
 *
 * @category Class
 * @description The role of the member in the organization.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Role
{
    /**
     * Possible values of this enum
     */
    public const OWNER = 'Owner';

    public const SUPER_ADMIN = 'SuperAdmin';

    public const BUSINESS = 'Business';

    public const SITE_ACCESS = 'SiteAccess';

    public const SUPPORT = 'Support';

    public const SYSADMIN = 'Sysadmin';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OWNER,
            self::SUPER_ADMIN,
            self::BUSINESS,
            self::SITE_ACCESS,
            self::SUPPORT,
            self::SYSADMIN
        ];
    }
}


