<?php
/**
 * WebserverKind
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.13.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * WebserverKind Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebserverKind
{
    /**
     * Possible values of this enum
     */
    public const LITE_SPEED = 'liteSpeed';

    public const OPEN_LITE_SPEED = 'openLiteSpeed';

    public const DUMMY_WEB_SERVER = 'dummyWebServer';

    public const APACHE = 'apache';

    public const NGINX = 'nginx';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LITE_SPEED,
            self::OPEN_LITE_SPEED,
            self::DUMMY_WEB_SERVER,
            self::APACHE,
            self::NGINX
        ];
    }
}


